- name: Create the OCNE Environment and Kubernetes Module
  ansible.builtin.shell: |
    olcnectl environment create --config-file environment.yaml
    olcnectl module create --config-file environment.yaml
    olcnectl module validate --config-file environment.yaml
    olcnectl module install --config-file environment.yaml
    olcnectl module instances --config-file environment.yaml