# mkdir -p $HOME/.kube
# sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
# sudo chown $(id -u):$(id -g) $HOME/.kube/config
# export KUBECONFIG=$HOME/.kube/config
# echo 'export KUBECONFIG=$HOME/.kube/config' >> $HOME/.bashrc

- name: Create the .kube directory
  ansible.builtin.file:
    path: $HOME/.kube
    state: directory
    mode: '0755'

- name: Copy the kube config file
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/opc/.kube/config
    owner: opc
    group: opc
    mode: '0644'
    remote_src: yes
  become: yes
  become_method: sudo

- name: Export the kube context and setup kubectl
  ansible.builtin.shell: |
    export KUBECONFIG=$HOME/.kube/config
    echo 'export KUBECONFIG=$HOME/.kube/config' >> $HOME/.bashrc