- hosts: all
  name: Provision OCNE and Verrazzano

  roles:
    - ocne/bootstrap-platform-api
    - ocne/bootstrap-platform-agent
    - ocne/environment
    - ocne/kubectl
    - verrazzano/install-platform-operator
    - verrazzano/install-v8o